If (-not ($Devices = $Variables.EnabledDevices | Where-Object { $_.Type -eq "CPU" -or $_.Type -eq "INTEL" -or ($_.Type -eq "AMD" -and $_.OpenCL.ClVersion -ge "OpenCL C 2.0") -or ($_.Type -eq "NVIDIA" -and $_.OpenCL.DriverVersion -ge "510.00") })) { Return }

$Uri = "https://github.com/doktor83/SRBMiner-Multi/releases/download/2.2.6/SRBMiner-Multi-2-2-6-win64.zip"
$Name = (Get-Item $MyInvocation.MyCommand.Path).BaseName
$Path = ".\Bin\$($Name)\SRBMiner-MULTI.exe"
$DeviceEnumerator = "Type_Vendor_Slot"
$Protocol = @{ "ethproxy" = " --esm 1"; "nicehash" = " --esm 2" }

# Algorithm parameter values are case sensitive!
$Algorithms = [PSCustomObject[]]@( 
    [PSCustomObject]@{ Algorithms = @("0x10");                     Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 45); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm 0x10") }
    [PSCustomObject]@{ Algorithms = @("Argon2d16000");             Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm argon2d_16000") }
    [PSCustomObject]@{ Algorithms = @("Argon2d500");               Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(45, 45); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm argon2d_dynamic") }
    [PSCustomObject]@{ Algorithms = @("Argon2Chukwa");             Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(45, 45); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm argon2id_chukwa") }
    [PSCustomObject]@{ Algorithms = @("Argon2Chukwa2");            Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(45, 45); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm argon2id_chukwa2") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2");               Type = "AMD"; Fee = @(0.01);         MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "Blake3");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "IronFish");   Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "HeavyHash");  Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "kHeavyHash"); Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "SHA256dt");   Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "SHA512256d"); Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm autolykos2", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("Blake2b");                  Type = "AMD"; Fee = @(0);            MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm blake2b") } # FPGA
#   [PSCustomObject]@{ Algorithms = @("Blake2s");                  Type = "AMD"; Fee = @(0);            MinMemGiB = 1;                                            Minerset = 3; WarmupTimes = @(45, 15); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm blake2s") } # ASIC
    [PSCustomObject]@{ Algorithms = @("Blake3");                   Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("IronFish");                 Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("CryptonightCcx");           Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm cryptonight_ccx") }
    [PSCustomObject]@{ Algorithms = @("CryptonightGpu");           Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(60, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm cryptonight_gpu") }
    [PSCustomObject]@{ Algorithms = @("CryptonightHeavyXhv");      Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm cryptonight_xhv") }
    [PSCustomObject]@{ Algorithms = @("CryptonightTalleo");        Type = "AMD"; Fee = @(0);            MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(60, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm cryptonight_talleo") }
    [PSCustomObject]@{ Algorithms = @("CryptonightTurtle");        Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm cryptonight_turtle") } # TeamRedMiner-v0.10.12 is fastest
    [PSCustomObject]@{ Algorithms = @("CryptonightUpx");           Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(60, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm cryptonight_upx") }
    [PSCustomObject]@{ Algorithms = @("CurveHash");                Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 1; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm curvehash") }
    [PSCustomObject]@{ Algorithms = @("DynamoCoin");               Type = "AMD"; Fee = @(0.01);         MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm dynamo") }
    [PSCustomObject]@{ Algorithms = @("DynexSolve");               Type = "AMD"; Fee = @(0.025);        MinMemGiB = 3;                                            MinerSet = 2; WarmupTimes = @(45, 45); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm dynex") }
    [PSCustomObject]@{ Algorithms = @("DynexSolve", "Blake3");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = 3;                                            MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm dynex", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("DynexSolve", "IronFish");   Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = 3;                                            MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm dynex", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("EtcHash");                  Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash") } # PhoenixMiner-v6.2c may be faster, but I see lower speed at the pool
    [PSCustomObject]@{ Algorithms = @("EtcHash", "Blake3");        Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "IronFish");      Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "HeavyHash");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "kHeavyHash");    Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "SHA256dt");      Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "SHA512256d");    Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm etchash", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("Ethash");                   Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash") } # PhoenixMiner-v6.2c may be faster, but I see lower speed at the pool
    [PSCustomObject]@{ Algorithms = @("Ethash", "Blake3");         Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "IronFish");       Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "Heavyhash");      Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "kHeavyhash");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "SHA256dt");       Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "SHA512256d");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ethash", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("EvrProgPow");               Type = "AMD"; Fee = @(0.0085);       MinMemGiB = $MinerPools[0].EvrProgPow.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(60, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm evrprogpow") }
    [PSCustomObject]@{ Algorithms = @("FiroPow");                  Type = "AMD"; Fee = @(0.0085);       MinMemGiB = $MinerPools[0].FiroPow.DAGSizeGiB + 1.24;     Minerset = 1; WarmupTimes = @(60, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm firopow") }
    [PSCustomObject]@{ Algorithms = @("HeavyHash");                Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(45, 15); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm heavyhash") } # FPGA
#   [PSCustomObject]@{ Algorithms = @("HeavyHash", "Autolykos2");  Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Autolykos2.DAGSizeGiB + 1.24;  Minerset = 2; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm heavyhash", " --algorithm autolykos2") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("HeavyHash", "EtcHash");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Etchash.DAGSizeGiB + 1.24;     Minerset = 2; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm heavyhash", " --algorithm etchash") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("Heavyhash", "Ethash");      Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Ethash.DAGSizeGiB + 1.24;      Minerset = 2; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm heavyhash", " --algorithm ethash") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("K12");                      Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 3; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm k12") } # ASIC
    [PSCustomObject]@{ Algorithms = @("KawPow");                   Type = "AMD"; Fee = @(0.0085);       MinMemGiB = $MinerPools[0].KawPow.DAGSizeGiB + 1.24;      Minerset = 1; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm kawpow") }
#   [PSCustomObject]@{ Algorithms = @("Keccak");                   Type = "AMD"; Fee = @(0);            MinMemGiB = 1;                                            Minerset = 3; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm keccak") } # ASIC
    [PSCustomObject]@{ Algorithms = @("kHeavyHash");               Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm kaspa") }
#   [PSCustomObject]@{ Algorithms = @("kHeavyHash", "Autolykos2"); Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Autolykos2.DAGSizeGiB + 1.24;  Minerset = 2; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm kaspa", " --algorithm autolykos2") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("kHeavyhash", "EtcHash");    Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].EtcHash.DAGSizeGiB + 1.24;     Minerset = 2; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm kaspa", " --algorithm etchash") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("kHeavyhash", "Ethash");     Type = "AMD"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Ethash.DAGSizeGiB + 1.24;      Minerset = 2; WarmupTimes = @(60, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm kaspa", " --algorithm ethash") } # No dual mining kernel
    [PSCustomObject]@{ Algorithms = @("Lyra2v2Webchain");          Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm lyra2v2_webchain") }
    [PSCustomObject]@{ Algorithms = @("ProgPowEpic");              Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowEpic.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm progpow_epic") }
    [PSCustomObject]@{ Algorithms = @("ProgPowSero");              Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowSero.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm progpow_sero") }
    [PSCustomObject]@{ Algorithms = @("ProgPowVeil");              Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowVeil.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm progpow_veil") }
    [PSCustomObject]@{ Algorithms = @("ProgPowVeriblock");         Type = "AMD"; Fee = @(0.0065);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm progpow_veriblock") }
    [PSCustomObject]@{ Algorithms = @("ProgPowZano");              Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowZano.DAGSizeGiB + 1.24; MinerSet = 0; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm progpow_zano") }
    [PSCustomObject]@{ Algorithms = @("Pufferfish2BMB");           Type = "AMD"; Fee = @(0.01);         MinMemGiB = 8;                                            Minerset = 2; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm pufferfish2bmb") }
    [PSCustomObject]@{ Algorithms = @("SHA256dt");                 Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 20); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("SHA3d");                    Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm sha3d") } # FPGA
    [PSCustomObject]@{ Algorithms = @("SHA512256d");               Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("UbqHash");                  Type = "AMD"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].UbqHash.DAGSizeGiB + 1.24;     Minerset = 1; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm ubqhash") }
    [PSCustomObject]@{ Algorithms = @("VerusHash");                Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm verushash") }
    [PSCustomObject]@{ Algorithms = @("VertHash");                 Type = "AMD"; Fee = @(0.0125);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 15); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm verthash --verthash-dat-path ..\.$($Variables.VerthashDatPath)") }
    [PSCustomObject]@{ Algorithms = @("Yescrypt");                 Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(90, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm yescrypt --log-file t.log") }
    [PSCustomObject]@{ Algorithms = @("YescryptR8");               Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(90, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm yescryptr8") }
    [PSCustomObject]@{ Algorithms = @("YescryptR16");              Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(90, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm yescryptr16") }
    [PSCustomObject]@{ Algorithms = @("YescryptR32");              Type = "AMD"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(90, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --gpu-auto-tune 2 --disable-cpu --disable-gpu-intel --disable-gpu-nvidia --algorithm yescryptr32") }

    [PSCustomObject]@{ Algorithms = @("Argon2d16000");         Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm argon2d_16000") }
    [PSCustomObject]@{ Algorithms = @("Argon2d500");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm argon2d_dynamic") }
    [PSCustomObject]@{ Algorithms = @("Argon2Chukwa");         Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm argon2id_chukwa") }
    [PSCustomObject]@{ Algorithms = @("Argon2Chukwa2");        Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm argon2id_chukwa2") }
#   [PSCustomObject]@{ Algorithms = @("Autolykos2");           Type = "CPU"; Fee = @(0.01);   Minerset = 3; WarmupTimes = @(120, 15); ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm autolykos2 --gpu-autolykos2-preload 3") } # Not profitable with CPU
    [PSCustomObject]@{ Algorithms = @("Blake2b");              Type = "CPU"; Fee = @(0);      MinerSet = 0; WarmupTimes = @(90, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm blake2b") } # FPGA
#   [PSCustomObject]@{ Algorithms = @("Blake2s");              Type = "CPU"; Fee = @(0);      Minerset = 3; WarmupTimes = @(30, 35);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm blake2s") } # ASIC
    [PSCustomObject]@{ Algorithms = @("Blake3");               Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("Ironfish");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("CryptonightCcx");       Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cryptonight_ccx") }
    [PSCustomObject]@{ Algorithms = @("CryptonightGpu");       Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(45, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cryptonight_gpu") }
    [PSCustomObject]@{ Algorithms = @("CryptonightHeavyxXhv"); Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cryptonight_xhv") }
    [PSCustomObject]@{ Algorithms = @("CryptonightTalleo");    Type = "CPU"; Fee = @(0);      Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cryptonight_talleo") }
    [PSCustomObject]@{ Algorithms = @("CryptonightTurtle");    Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cryptonight_turtle") }
    [PSCustomObject]@{ Algorithms = @("CryptonightUpx");       Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cryptonight_upx") }
    [PSCustomObject]@{ Algorithms = @("CpuPower");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm cpupower") }
    [PSCustomObject]@{ Algorithms = @("CurveHash");            Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 20);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm curvehash") }
    [PSCustomObject]@{ Algorithms = @("DynamoCoin");           Type = "CPU"; Fee = @(0.01);   Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm dynamo") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash");              Type = "CPU"; Fee = @(0.0065); Minerset = 3; WarmupTimes = @(30, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm etchash") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("Ethash");               Type = "CPU"; Fee = @(0.0065); Minerset = 3; WarmupTimes = @(30, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm ethash") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("EvrProgPow");           Type = "CPU"; Fee = @(0.0085); Minerset = 3; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm evrprogpow") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("FiroPow");              Type = "CPU"; Fee = @(0.0085); Minerset = 3; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm firopow") } # Not profitable with CPU
    [PSCustomObject]@{ Algorithms = @("Ghostrider");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 60);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm ghostrider") }
    [PSCustomObject]@{ Algorithms = @("HeavyHash");            Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(45, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm heavyhash") }
#   [PSCustomObject]@{ Algorithms = @("K12");                  Type = "CPU"; Fee = @(0);      MinerSet = 3; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm K12") } # ASIC
#   [PSCustomObject]@{ Algorithms = @("KawPow");               Type = "CPU"; Fee = @(0.0085); Minerset = 3; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm kawpow") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("Keccak");               Type = "CPU"; Fee = @(0);      Minerset = 3; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm keccak") } # ASIC
    [PSCustomObject]@{ Algorithms = @("kHeavyHash");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("Lyra2v2Webchain");      Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm lyra2v2_webchain") }
    [PSCustomObject]@{ Algorithms = @("Mike");                 Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm mike") }
    [PSCustomObject]@{ Algorithms = @("Minotaur");             Type = "CPU"; Fee = @(0);      Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm minotaur") }
    [PSCustomObject]@{ Algorithms = @("MinotaurX");            Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(20, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm minotaurx") }
    [PSCustomObject]@{ Algorithms = @("Panthera");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm panthera") }
#   [PSCustomObject]@{ Algorithms = @("ProgPowEpic");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm progpow_epic") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("ProgPowSero");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm progpow_sero") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("ProgPowVeil");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm progpow_veil") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("ProgPowVeriblock");     Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm progpow_veriblock") } # Not profitable with CPU
#   [PSCustomObject]@{ Algorithms = @("ProgPowZano");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm progpow_zano") } # Not profitable with CPU
    [PSCustomObject]@{ Algorithms = @("Pufferfish2BMB");       Type = "CPU"; Fee = @(0.01);   Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm pufferfish2bmb") }
    [PSCustomObject]@{ Algorithms = @("SHA256dt");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("SHA512256d");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 40);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("RandomxArq");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomarq --Randomx-use-1gb-pages") } # FPGA
    [PSCustomObject]@{ Algorithms = @("RandomxEpic");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomepic") }
    [PSCustomObject]@{ Algorithms = @("RandomGrft");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomgrft --Randomx-use-1gb-pages") }
    [PSCustomObject]@{ Algorithms = @("RandomHash2");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomarq --Randomx-use-1gb-pages") }
    [PSCustomObject]@{ Algorithms = @("RandomL");              Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randoml --Randomx-use-1gb-pages") }
    [PSCustomObject]@{ Algorithms = @("RandomSfx");            Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomsfx --Randomx-use-1gb-pages") }
    [PSCustomObject]@{ Algorithms = @("RandomWow");            Type = "CPU"; Fee = @(0);      Minerset = 2; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomwow --Randomx-use-1gb-pages") }
#   [PSCustomObject]@{ Algorithms = @("Randomx");              Type = "CPU"; Fee = @(0.0085); Minerset = 3; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm Randomx --Randomx-use-1gb-pages") } # ASIC
    [PSCustomObject]@{ Algorithms = @("RandomxKeva");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomkeva --Randomx-use-1gb-pages") }
    [PSCustomObject]@{ Algorithms = @("RandomxL");             Type = "CPU"; Fee = @(0);      Minerset = 2; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm Randomxl --Randomx-use-1gb-pages") } # XmRig-v6.18.1 is fastest
    [PSCustomObject]@{ Algorithms = @("RandomYada");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm randomyada") }
    [PSCustomObject]@{ Algorithms = @("ScryptN2");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 20);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm scryptn2") }
    [PSCustomObject]@{ Algorithms = @("SHA3d");                Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm sha3d") } # FPGA
#   [PSCustomObject]@{ Algorithms = @("UbqHash");              Type = "CPU"; Fee = @(0.0065); Minerset = 3; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm ubqhash") } # Not profitable with CPU
    [PSCustomObject]@{ Algorithms = @("VertHash");             Type = "CPU"; Fee = @(0.01);   Minerset = 2; WarmupTimes = @(30, 20);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm verthash --verthash-dat-path ..\.$($Variables.VerthashDatPath)") }
    [PSCustomObject]@{ Algorithms = @("VerusHash");            Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(30, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm verushash") }
    [PSCustomObject]@{ Algorithms = @("Xdag");                 Type = "CPU"; Fee = @(0.01);   Minerset = 2; WarmupTimes = @(60, 0);   ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm xdag") }
    [PSCustomObject]@{ Algorithms = @("YescryptR16");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yescryptr16") }
    [PSCustomObject]@{ Algorithms = @("YescryptR32");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 45);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yescryptr32") }
    [PSCustomObject]@{ Algorithms = @("YescryptR8");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yescryptr8") }
    [PSCustomObject]@{ Algorithms = @("Yespower");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 40);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespower") }
    [PSCustomObject]@{ Algorithms = @("Yespower2b");           Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespower2b") }
    [PSCustomObject]@{ Algorithms = @("YespowerARWN");         Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowerarwn") }
    [PSCustomObject]@{ Algorithms = @("YespowerIc");           Type = "CPU"; Fee = @(0)     ; Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespoweric") }
    [PSCustomObject]@{ Algorithms = @("YespowerIots");         Type = "CPU"; Fee = @(0)     ; Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespoweriots") }
    [PSCustomObject]@{ Algorithms = @("YespowerItc");          Type = "CPU"; Fee = @(0)     ; Minerset = 2; WarmupTimes = @(60, 30);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespoweritc") }
    [PSCustomObject]@{ Algorithms = @("YespowerLitb");         Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowerlitb") }
    [PSCustomObject]@{ Algorithms = @("YespowerLtncg");        Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowerltncg") }
    [PSCustomObject]@{ Algorithms = @("YespowerMgpc");         Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowermgpc") }
    [PSCustomObject]@{ Algorithms = @("YespowerR16");          Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowerr16") }
    [PSCustomObject]@{ Algorithms = @("YespowerRes");          Type = "CPU"; Fee = @(0);      Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespoweres") }
    [PSCustomObject]@{ Algorithms = @("YespowerSugar");        Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowersugar") }
    [PSCustomObject]@{ Algorithms = @("YespowerTide");         Type = "CPU"; Fee = @(0);      Minerset = 2; WarmupTimes = @(60, 25);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowertide") }
    [PSCustomObject]@{ Algorithms = @("YespowerUrx");          Type = "CPU"; Fee = @(0);      Minerset = 1; WarmupTimes = @(60, 15);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yespowerurx") }
    [PSCustomObject]@{ Algorithms = @("Yescrypt");             Type = "CPU"; Fee = @(0.0085); Minerset = 2; WarmupTimes = @(90, 20);  ExcludePools = @(@(), @()); Arguments = @(" --disable-gpu --algorithm yescrypt") }

    [PSCustomObject]@{ Algorithms = @("Autolykos2");               Type = "INTEL"; Fee = @(0.01);         MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  Minerset = 1; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "Blake3");     Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "IronFish");   Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "HeavyHash");  Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "kHeavyHash"); Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "SHA256dt");   Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "SHA512256d"); Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm autolykos2", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("Blake3");                   Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("IronFish");                 Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("DynexSolve");               Type = "INTEL"; Fee = @(0.025);        MinMemGiB = 3;                                            MinerSet = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm dynex") }
    [PSCustomObject]@{ Algorithms = @("EtcHash");                  Type = "INTEL"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash", "Blake3");        Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash", " --algorithm blake3_alephium") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash", "IronFish");      Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash", " --algorithm blake3_ironfish") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash", "HeavyHash");     Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash", " --algorithm heavyhash") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash", "kHeavyHash");    Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash", " --algorithm kaspa") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash", "SHA256dt");      Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash", " --algorithm sha256dt") }
#   [PSCustomObject]@{ Algorithms = @("EtcHash", "SHA512256d");    Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm etchash", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("Ethash");                   Type = "INTEL"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash") }
#   [PSCustomObject]@{ Algorithms = @("Ethash", "Blake3");         Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash", " --algorithm blake3_alephium") }
#   [PSCustomObject]@{ Algorithms = @("Ethash", "IronFish");       Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash", " --algorithm blake3_ironfish") }
#   [PSCustomObject]@{ Algorithms = @("Ethash", "Heavyhash");      Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash", " --algorithm heavyhash") }
#   [PSCustomObject]@{ Algorithms = @("Ethash", "kHeavyhash");     Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash", " --algorithm kaspa") }
#   [PSCustomObject]@{ Algorithms = @("Ethash", "SHA256dt");       Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash", " --algorithm sha256dt") }
#   [PSCustomObject]@{ Algorithms = @("Ethash", "SHA512256d");     Type = "INTEL"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ethash", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("HeavyHash");                Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("kHeavyHash");               Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 1; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("SHA256dt");                 Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 1; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("SHA3d");                    Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm sha3d") } # FPGA
    [PSCustomObject]@{ Algorithms = @("SHA512256d");               Type = "INTEL"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 1; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("UbqHash");                  Type = "INTEL"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].UbqHash.DAGSizeGiB + 1.24;     Minerset = 2; WarmupTimes = @(45, 15); ExcludeGPUArchitecture = @(); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-nvidia --algorithm ubqhash") }

    [PSCustomObject]@{ Algorithms = @("Autolykos2");               Type = "NVIDIA"; Fee = @(0.01);         MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  Minerset = 1; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "Blake3");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "IronFish");   Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "HeavyHash");  Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "kHeavyHash"); Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "SHA256dt");   Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("Autolykos2", "SHA512256d"); Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Autolykos2.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm autolykos2", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("Blake3");                   Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("IronFish");                 Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("DynamoCoin");               Type = "NVIDIA"; Fee = @(0.01);         MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm dynamo") } # Algorithm 'dynamo' supports only 'pool' mode (yiimp stratum compatibility removed)
    [PSCustomObject]@{ Algorithms = @("DynexSolve");               Type = "NVIDIA"; Fee = @(0.025);        MinMemGiB = 3;                                            Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm dynex") }
    [PSCustomObject]@{ Algorithms = @("DynexSolve", "Blake3");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = 3;                                            MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm dynex", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("DynexSolve", "IronFish");   Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = 3;                                            MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm dynex", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("EtcHash");                  Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash") } # PhoenixMiner-v6.2c may be faster, but I see lower speed at the pool
    [PSCustomObject]@{ Algorithms = @("EtcHash", "Blake3");        Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "IronFish");      Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "HeavyHash");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "kHeavyHash");    Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "SHA256dt");      Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("EtcHash", "SHA512256d");    Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Etchash.DAGSizeGiB + 1.24;     MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm etchash", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("Ethash");                   Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash") } # PhoenixMiner-v6.2c may be faster, but I see lower speed at the pool
    [PSCustomObject]@{ Algorithms = @("Ethash", "Blake3");         Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash", " --algorithm blake3_alephium") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "IronFish");       Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash", " --algorithm blake3_ironfish") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "Heavyhash");      Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash", " --algorithm heavyhash") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "kHeavyhash");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash", " --algorithm kaspa") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "SHA256dt");       Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash", " --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("Ethash", "SHA512256d");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[0].Ethash.DAGSizeGiB + 1.24;      MinerSet = 0; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ethash", " --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("EvrProgPow");               Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = $MinerPools[0].EvrProgPow.DAGSizeGiB + 1.24;  MinerSet = 0; WarmupTimes = @(60, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm evrprogpow") }
    [PSCustomObject]@{ Algorithms = @("FiroPow");                  Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = $MinerPools[0].FiroPow.DAGSizeGiB + 1.24;     Minerset = 1; WarmupTimes = @(60, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm firopow") }
    [PSCustomObject]@{ Algorithms = @("HeavyHash");                Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm heavyhash") } # FPGA
#   [PSCustomObject]@{ Algorithms = @("HeavyHash", "Autolykos2");  Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Autolykos2.DAGSizeGiB + 1.24;  Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm heavyhash", " --algorithm autolykos2") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("HeavyHash", "EtcHash");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Etchash.DAGSizeGiB + 1.24;     Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm heavyhash", " --algorithm etchash") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("Heavyhash", "Ethash");      Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Ethash.DAGSizeGiB + 1.24;      Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm heavyhash", " --algorithm ethash") } # No dual mining kernel
    [PSCustomObject]@{ Algorithms = @("KawPow");                   Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = $MinerPools[0].KawPow.DAGSizeGiB + 1.24;      Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm kawpow") }
    [PSCustomObject]@{ Algorithms = @("kHeavyHash");               Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 1; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm kaspa") }
#   [PSCustomObject]@{ Algorithms = @("kHeavyHash", "Autolykos2"); Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Autolykos2.DAGSizeGiB + 1.24;  Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm kaspa", " --algorithm autolykos2") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("kHeavyhash", "EtcHash");    Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].EtcHash.DAGSizeGiB + 1.24;     Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm kaspa", " --algorithm etchash") } # No dual mining kernel
#   [PSCustomObject]@{ Algorithms = @("kHeavyhash", "Ethash");     Type = "NVIDIA"; Fee = @(0.0065, 0.01); MinMemGiB = $MinerPools[1].Ethash.DAGSizeGiB + 1.24;      Minerset = 2; WarmupTimes = @(45, 60); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm kaspa", " --algorithm ethash") } # No dual mining kernel
    [PSCustomObject]@{ Algorithms = @("Lyra2v2Webchain");          Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 2; WarmupTimes = @(30, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm lyra2v2_webchain") }
    [PSCustomObject]@{ Algorithms = @("ProgPowEpic");              Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowEpic.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm progpow_epic") }
    [PSCustomObject]@{ Algorithms = @("ProgPowSero");              Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowSero.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm progpow_sero") }
    [PSCustomObject]@{ Algorithms = @("ProgPowVeil");              Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowVeil.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm progpow_veil") }
    [PSCustomObject]@{ Algorithms = @("ProgPowVeriblock");         Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = 2;                                            Minerset = 2; WarmupTimes = @(45, 30); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm progpow_veriblock") }
    [PSCustomObject]@{ Algorithms = @("ProgPowZano");              Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].ProgPowZano.DAGSizeGiB + 1.24; Minerset = 2; WarmupTimes = @(45, 0);  ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm progpow_zano") }
    [PSCustomObject]@{ Algorithms = @("SHA256dt");                 Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 15); ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm sha256dt") }
    [PSCustomObject]@{ Algorithms = @("SHA3d");                    Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 1;                                            MinerSet = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm sha3d") } # FPGA
    [PSCustomObject]@{ Algorithms = @("SHA512256d");               Type = "NVIDIA"; Fee = @(0.0085);       MinMemGiB = 1;                                            Minerset = 0; WarmupTimes = @(30, 0);  ExcludeGPUArchitecture = @("Other"); ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm sha512_256d_radiant") }
    [PSCustomObject]@{ Algorithms = @("UbqHash");                  Type = "NVIDIA"; Fee = @(0.0065);       MinMemGiB = $MinerPools[0].UbqHash.DAGSizeGiB + 1.24;     Minerset = 2; WarmupTimes = @(45, 15); ExcludeGPUArchitecture = @();        ExcludePools = @(@(), @()); Arguments = @(" --disable-cpu --disable-gpu-amd --disable-gpu-intel --algorithm ubqhash") }
)

$Algorithms = $Algorithms | Where-Object MinerSet -LE $Config.MinerSet
$Algorithms = $Algorithms | Where-Object { $MinerPools[0].($_.Algorithms[0]).PoolPorts -and (-not $_.Algorithms[1] -or $MinerPools[1].($_.Algorithms[1]).PoolPorts) }
$Algorithms = $Algorithms | Where-Object { $MinerPools[0].($_.Algorithms[0]).BaseName -notin $_.ExcludePools[0] -and (-not $_.Algorithms[1] -or $MinerPools[1].($_.Algorithms[1]).BaseName -notin $_.ExcludePools[1]) }

If ($Algorithms) { 

    # Allowed max loss for 1. algorithm
    # $GpuDualMaxLosses = @(2, 4, 7, 10, 15, 20, 30)
    $GpuDualMaxLosses = @()

    # # Build command sets for max loss
    $Algorithms | ForEach-Object { 
        If ($_.Algorithms[1]) { 
            ForEach ($GpuDualMaxLoss in $GpuDualMaxLosses) { 
                $_ | Add-Member GpuDualMaxLoss $GpuDualMaxLoss -Force
                $Algorithms += $_.PsObject.Copy()
            }
        }
    }

    $Devices | Select-Object Type, Model -Unique | ForEach-Object { 

        $Miner_Devices = $Devices | Where-Object Type -EQ $_.Type | Where-Object Model -EQ $_.Model
        $MinerAPIPort = [UInt16]($Config.APIPort + ($Miner_Devices.Id | Sort-Object -Top 1) + 1)

        $Algorithms | Where-Object Type -EQ $_.Type | ForEach-Object { 

            $MinMemGiB = $_.MinMemGiB

            If ($AvailableMiner_Devices = $Miner_Devices | Where-Object { $_.Type -eq "CPU" -or $_.MemoryGiB -gt $MinMemGiB } | Where-Object Architecture -notin $_.ExcludeGPUArchitecture) { 

                $Arguments = ""
                $Miner_Name = "$($Name)-$($AvailableMiner_Devices.Count)x$($AvailableMiner_Devices.Model)$(If ($_.Algorithms[1]) { "-$($_.Algorithms[0])&$($_.Algorithms[1])" })$(If ($_.GpuDualMaxLoss) { "-$($_.$GpuDualMaxLoss)" })" -replace ' '

                # Get arguments for available miner devices
                # $Arguments = Get-ArgumentsPerDevice -Arguments $Arguments -ExcludeArguments @("algorithm") -DeviceIDs $AvailableMiner_Devices.$DeviceEnumerator

                $Index = 0
                ForEach ($Algorithm in $_.Algorithms) { 
                    $Arguments += Switch ($MinerPools[$Index].$Algorithm.Protocol) { 
                        "minerproxy"   { " --esm 0"; Break }
                        "ethproxy"     { " --esm 0"; Break }
                        "ethstratum1"  { " --esm 1"; Break }
                        "ethstratum2"  { " --esm 2"; Break }
                        "ethstratumnh" { " --esm 2"; Break }
                    }
                    $Arguments += "$($_.Arguments[$Index]) --pool $($MinerPools[$Index].$Algorithm.Host):$($MinerPools[$Index].$Algorithm.PoolPorts | Select-Object -Last 1) --wallet $($MinerPools[$Index].$Algorithm.User)"
                    $Arguments += " --password $($MinerPools[$Index].$Algorithm.Pass)$(If ($MinerPools[$Index].$Algorithm.BaseName -eq "ProHashing" -and $Algorithm -eq "Ethash") { ",l=$((($AvailableMiner_Devices.Memory | Measure-Object -Minimum).Minimum) / 1GB - ($_.MinMemGiB - $MinerPools[$Index].$Algorithm.DAGSizeGiB))" })"
                    If ($MinerPools[$Index].$Algorithm.WorkerName) { $Arguments += " --worker $($MinerPools[$Index].$Algorithm.WorkerName)" }
                    $Arguments += If ($MinerPools[$Index].$Algorithm.PoolPorts[1]) { " --tls true" } Else { " --tls false" }

                    If ($_.GpuDualMaxLoss) { $Arguments += " --gpu-dual-max-loss 5" }
                    $Index ++
                }
                Remove-Variable Algorithm

                If (($AvailableMiner_Devices.Type | Select-Object -Unique) -eq "CPU") { 
                    $Arguments += " --cpu-threads $($AvailableMiner_Devices.CIM.NumberOfLogicalProcessors -1)"
                }
                Else { 
                    $Arguments += " --gpu-id $(($AvailableMiner_Devices.$DeviceEnumerator | Sort-Object -Unique | ForEach-Object { '{0:x}' -f $_ }) -join ',')"
                }

                If ($_.Algorithms[0] -eq "VertHash" -and (Get-Item -Path $Variables.VerthashDatPath -ErrorAction Ignore).length -ne 1283457024) { 
                    $PrerequisitePath = $Variables.VerthashDatPath
                    $PrerequisiteURI = "https://github.com/Minerx117/miners/releases/download/Verthash.Dat/VertHash.dat"
                }
                Else { 
                    $PrerequisitePath = ""
                    $PrerequisiteURI = ""
                }
                If ($_.Type -eq "CPU" -and $Variables.UseMinerTweaks) { $Arguments += " --disable-msr-tweaks" }

                [PSCustomObject]@{ 
                    Algorithms       = @($_.Algorithms | Select-Object)
                    API              = "SRBMiner"
                    Arguments        = ("$($Arguments) --api-rig-name $($Config.WorkerName) --api-enable --api-port $MinerAPIPort" -replace "\s+", " ").trim()
                    DeviceNames      = $AvailableMiner_Devices.Name
                    Fee              = $_.Fee # Dev fee
                    MinerSet         = $_.MinerSet
                    MinerUri         = "http://127.0.0.1:$($MinerAPIPort)/stats"
                    Name             = $Miner_Name
                    Path             = $Path
                    Port             = $MinerAPIPort
                    PrerequisitePath = $PrerequisitePath
                    PrerequisiteURI  = $PrerequisiteURI
                    Type             = $_.Type
                    URI              = $Uri
                    WarmupTimes      = $_.WarmupTimes # First value: Seconds until miner must send first sample, if no sample is received miner will be marked as failed; Second value: Seconds from first sample until miner sends stable hashrates that will count for benchmarking
                }
            }
        }
    }
}