<#
Copyright (c) 2018-2023 Nemo, MrPlus & UselessGuru

NemosMiner is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

NemosMiner is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
#>

<#
Product:        NemosMiner
Version:        5.0.2.3
Version date:   2023/12/20
#>

If (-not ($Devices = $Variables.EnabledDevices.Where({ ($_.Type -eq "AMD" -and $_.OpenCL.ClVersion -ge "OpenCL C 1.2") -or $_.Type -eq "INTEL" -or ($_.OpenCL.ComputeCapability -ge "5.0" -and $_.OpenCL.DriverVersion -ge [Version]"452.39.00") }))) { Return }

$URI = "https://github.com/andru-kun/wildrig-multi/releases/download/0.40.2a/wildrig-multi-windows-0.40.2a.zip"
$Name = (Get-Item $MyInvocation.MyCommand.Path).BaseName
$Path = "$PWD\Bin\$Name\wildrig.exe"
$DeviceEnumerator = "Type_Slot"

$Algorithms = @(
    [PSCustomObject]@{ Algorithm = "Aergo";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo aergo" }
    [PSCustomObject]@{ Algorithm = "Anime";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo anime" }
    [PSCustomObject]@{ Algorithm = "AstralHash";       Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-astralhash" }
#   [PSCustomObject]@{ Algorithm = "BCD";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 3; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bcd" } # ASIC
    [PSCustomObject]@{ Algorithm = "Bitcore";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bitcore" }
    [PSCustomObject]@{ Algorithm = "Blake2bBtcc";      Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2b-btcc" }
    [PSCustomObject]@{ Algorithm = "Blake2bGlt";       Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2b-glt" }
#   [PSCustomObject]@{ Algorithm = "Blake2s";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2s" } # ASIC
    [PSCustomObject]@{ Algorithm = "Blake3";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake3" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Bmw512";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bmw512" } # ASIC
    [PSCustomObject]@{ Algorithm = "Bitcore";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bitcore" }
    [PSCustomObject]@{ Algorithm = "C11";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo c11" }
    [PSCustomObject]@{ Algorithm = "CurveHash";        Type = "AMD"; Fee = @(0.01);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("GCN4");  ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo curvehash" } # https://github.com/andru-kun/wildrig-multi/issues/255
    [PSCustomObject]@{ Algorithm = "Dedal";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo dedal" } # CryptoDredge-v0.27.0 is fastest
    [PSCustomObject]@{ Algorithm = "EvrProgPow";       Type = "AMD"; Fee = @(0.0075); MinMemGiB = 0.62; MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo evrprogpow" } 
    [PSCustomObject]@{ Algorithm = "FiroPow";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 1.24; MinerSet = 0; WarmupTimes = @(55, 45);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo firopow" }
    [PSCustomObject]@{ Algorithm = "Ghostrider";       Type = "AMD"; Fee = @(0.01);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(180, 60); ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo ghostrider" }
    [PSCustomObject]@{ Algorithm = "GlobalHash";       Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-globalhash" }
    [PSCustomObject]@{ Algorithm = "HeavyHash";        Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 1; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo heavyhash" } # FPGA
    [PSCustomObject]@{ Algorithm = "Hex";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo hex" }
    [PSCustomObject]@{ Algorithm = "HMQ1725";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo hmq1725" } # CryptoDredge-v0.27.0 is fastest
    [PSCustomObject]@{ Algorithm = "JeongHash";        Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-jeonghash" }
    [PSCustomObject]@{ Algorithm = "KawPow";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 1; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo kawpow" } # TeamRedMiner-v0.10.14 is fastest on Navi
#   [PSCustomObject]@{ Algorithm = "Lyra2RE2";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2v2" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Lyra2RE3";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2v3" } # ASIC
    [PSCustomObject]@{ Algorithm = "Lyra2TDC";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2tdc" }
    [PSCustomObject]@{ Algorithm = "Lyra2vc0ban";      Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2vc0ban" }
    [PSCustomObject]@{ Algorithm = "MemeHash";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo memehash" }
    [PSCustomObject]@{ Algorithm = "MegaBtx";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo megabtx" }
    [PSCustomObject]@{ Algorithm = "Mike";             Type = "AMD"; Fee = @(0.01);   MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo mike" }
    [PSCustomObject]@{ Algorithm = "NexaPow";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 3;    Minerset = 2; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @("GCN4");  ExcludeGPUModel = ""; ExcludePools = @("NiceHash"); Arguments = " --algo nexapow" } # https://github.com/andru-kun/wildrig-multi/issues/255 & https://github.com/andru-kun/wildrig-multi/issues/277
#   [PSCustomObject]@{ Algorithm = "Nist5";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo nist5" } # ASIC
    [PSCustomObject]@{ Algorithm = "PadiHash";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-padihash" }
    [PSCustomObject]@{ Algorithm = "PawelHash";        Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-pawelhash" }
#   [PSCustomObject]@{ Algorithm = "Phi";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo phi" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Phi5";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo phi5" } # Algorithm is dead
    [PSCustomObject]@{ Algorithm = "ProgPowEthercore"; Type = "AMD"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-ethercore" }
    [PSCustomObject]@{ Algorithm = "ProgPowSero";      Type = "AMD"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-sero" }
    [PSCustomObject]@{ Algorithm = "ProgPowVeil";      Type = "AMD"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-veil" }
    [PSCustomObject]@{ Algorithm = "ProgPowVeriblock"; Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo vprogpow" }
    [PSCustomObject]@{ Algorithm = "ProgPowZ";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 0.62; MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpowz" }
#   [PSCustomObject]@{ Algorithm = "Pufferfish2BMB";   Type = "AMD"; Fee = @(0.01);   MinMemGiB = 8;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo pufferfish2" } # waiting for coin to resurrect
    [PSCustomObject]@{ Algorithm = "RWAHash";          Type = "AMD"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo rwahash" }
#   [PSCustomObject]@{ Algorithm = "Quark";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo quark" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Quibit";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo qui" } # ASIC
#   [PSCustomObject]@{ Algorithm = "SHA256";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other")  ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256" } # ASIC
#   [PSCustomObject]@{ Algorithm = "SHA256d";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other")  ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256d" } # ASIC
    [PSCustomObject]@{ Algorithm = "SHAndwich256";     Type = "AMD"; Fee = @(0.02);   MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skydoge" }
    [PSCustomObject]@{ Algorithm = "SHA256csm";        Type = "AMD"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256csm" }
    [PSCustomObject]@{ Algorithm = "SHA256t";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256t" } # Takes too long until it starts mining
    [PSCustomObject]@{ Algorithm = "SHA256q";          Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256q" }
    [PSCustomObject]@{ Algorithm = "SHA512256d";       Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha512256d" }
    [PSCustomObject]@{ Algorithm = "Skein2";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skein2" }
    [PSCustomObject]@{ Algorithm = "SkunkHash";        Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skunkhash" } # Algorithm is dead
    [PSCustomObject]@{ Algorithm = "Timetravel";       Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo timetravel" }
    [PSCustomObject]@{ Algorithm = "Timetravel10";     Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo timetravel10" }
    [PSCustomObject]@{ Algorithm = "Tribus";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo tribus" }
#   [PSCustomObject]@{ Algorithm = "X11";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X11ghost";         Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11ghost" } # ASIC
    [PSCustomObject]@{ Algorithm = "X11k";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11k" }
#   [PSCustomObject]@{ Algorithm = "X12";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x12" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X13";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x13" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X14";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x14" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X15";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x15" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X16r";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 3; WarmupTimes = @(30, 60);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16r" } # ASIC
    [PSCustomObject]@{ Algorithm = "X16rt";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16rt" } # FPGA
    [PSCustomObject]@{ Algorithm = "X16rv2";           Type = "AMD"; Fee = @(0.0075); MinMemGiB = 3;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16rv2" }
    [PSCustomObject]@{ Algorithm = "X16s";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16s" } # FPGA
    [PSCustomObject]@{ Algorithm = "X17";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x17" }
    [PSCustomObject]@{ Algorithm = "X18";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x18" }
    [PSCustomObject]@{ Algorithm = "X21s";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(120, 45); ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x21s" } # TeamRedMiner-v0.10.14 is fastest
    [PSCustomObject]@{ Algorithm = "X22";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x22" }
    [PSCustomObject]@{ Algorithm = "X22i";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x22i" }
    [PSCustomObject]@{ Algorithm = "X25x";             Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x25x" }
    [PSCustomObject]@{ Algorithm = "X33";              Type = "AMD"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x33" }
    [PSCustomObject]@{ Algorithm = "Xevan";            Type = "AMD"; Fee = @(0.0075); MinMemGiB = 3;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo xevan --gpu-threads 1" } # No hashrate on time for old GPUs

    [PSCustomObject]@{ Algorithm = "Aergo";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo aergo --watchdog" }
    [PSCustomObject]@{ Algorithm = "Anime";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo anime --watchdog" }
    [PSCustomObject]@{ Algorithm = "AstralHash";       Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-astralhash --watchdog" }
    [PSCustomObject]@{ Algorithm = "BCD";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 3; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bcd --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "Bitcore";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bitcore --watchdog" }
    [PSCustomObject]@{ Algorithm = "Blake2bBtcc";      Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2b-btcc --watchdog" }
    [PSCustomObject]@{ Algorithm = "Blake2bGlt";       Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2b-glt --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Blake2s";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2s" } # ASIC
    [PSCustomObject]@{ Algorithm = "Blake3";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake3" }
#   [PSCustomObject]@{ Algorithm = "Bmw512";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bmw512 --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "C11";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 1; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo c11 --watchdog" }
    [PSCustomObject]@{ Algorithm = "CurveHash";        Type = "INTEL"; Fee = @(0.01);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo curvehash --watchdog" }
    [PSCustomObject]@{ Algorithm = "Dedal";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo dedal --watchdog" } # CryptoDredge-v0.27.0 is fastest
    [PSCustomObject]@{ Algorithm = "EvrProgPow";       Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 1; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo evrprogpow --watchdog" }
    [PSCustomObject]@{ Algorithm = "FiroPow";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 1.24; Minerset = 1; WarmupTimes = @(55, 45);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo firopow --watchdog" }
    [PSCustomObject]@{ Algorithm = "Ghostrider";       Type = "INTEL"; Fee = @(0.01);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(180, 60); ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo ghostrider --watchdog" }
    [PSCustomObject]@{ Algorithm = "GlobalHash";       Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-globalhash --watchdog" }
    [PSCustomObject]@{ Algorithm = "Hex";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo hex --watchdog" }
#   [PSCustomObject]@{ Algorithm = "HeavyHash";        Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 1; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo heavyhash" } # FPGA, Not yet supported on Nvidia
    [PSCustomObject]@{ Algorithm = "HMQ1725";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 1; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo hmq1725 --watchdog" } # CryptoDredge-v0.27.0 is fastest
    [PSCustomObject]@{ Algorithm = "JeongHash";        Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-jeonghash --watchdog" } # Trex-v0.26.8 is fastest
    [PSCustomObject]@{ Algorithm = "KawPow";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 0.90; Minerset = 1; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo kawpow --watchdog" } # NBMiner-v42.3 is fastest
#   [PSCustomObject]@{ Algorithm = "Lyra2RE2";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2v2 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Lyra2RE3";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2v3 --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "Lyra2TDC";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2tdc --watchdog" }
    [PSCustomObject]@{ Algorithm = "Lyra2vc0ban";      Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2vc0ban --watchdog" }
    [PSCustomObject]@{ Algorithm = "MemeHash";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo memehash --watchdog" }
    [PSCustomObject]@{ Algorithm = "MegaBtx";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo megabtx --watchdog" }
    [PSCustomObject]@{ Algorithm = "Mike";             Type = "INTEL"; Fee = @(0.01);   MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo mike --watchdog" }
    [PSCustomObject]@{ Algorithm = "NexaPow";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 3;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @("NiceHash"); Arguments = " --algo nexapow --watchdog" } # https://github.com/andru-kun/wildrig-multi/issues/277
#   [PSCustomObject]@{ Algorithm = "Nist5";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo nist5 --watchdog" }
    [PSCustomObject]@{ Algorithm = "PadiHash";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-padihash --watchdog" }
    [PSCustomObject]@{ Algorithm = "PawelHash";        Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-pawelhash --watchdog" } # Trex-v0.26.8 is fastest
#   [PSCustomObject]@{ Algorithm = "Phi";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo phi --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Phi5";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo phi5 --watchdog" } # Algorithm is dead
    [PSCustomObject]@{ Algorithm = "ProgPowEthercore"; Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-ethercore --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowSero";      Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-sero --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowVeil";      Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-veil --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowVeriblock"; Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo vprogpow --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowZ";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 1; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpowz --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Pufferfish2BMB";   Type = "INTEL"; Fee = @(0.01);   MinMemGiB = 8;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo pufferfish2 --watchdog" } # waiting for coin to resurrect
    [PSCustomObject]@{ Algorithm = "RWAHash";          Type = "INTEL"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo rwahash --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Quark";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo quark" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Quibit";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo qui" } # ASIC
#   [PSCustomObject]@{ Algorithm = "SHA256";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256" } # ASIC
#   [PSCustomObject]@{ Algorithm = "SHA256d";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256d" } # ASIC
    [PSCustomObject]@{ Algorithm = "SHAndwich256";     Type = "INTEL"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skydoge --watchdog" } # Trex-v0.26.8 is fastest
    [PSCustomObject]@{ Algorithm = "SHA256csm";        Type = "INTEL"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256csm --watchdog" }
    [PSCustomObject]@{ Algorithm = "SHA256t";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256t --watchdog" }
    [PSCustomObject]@{ Algorithm = "SHA256q";          Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256q --watchdog" }
    [PSCustomObject]@{ Algorithm = "SHA512256d";       Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha512256d --watchdog" }
    [PSCustomObject]@{ Algorithm = "Skein2";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(90, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skein2 --watchdog" } # CcminerAlexis78-v1.5.2 is fastest
    [PSCustomObject]@{ Algorithm = "SkunkHash";        Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(90, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skunkhash --watchdog" } # Algorithm is dead
    [PSCustomObject]@{ Algorithm = "Timetravel";       Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo timetravel --watchdog" }
    [PSCustomObject]@{ Algorithm = "Timetravel10";     Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo timetravel10 --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Tribus";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo tribus --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X11";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X11ghost";         Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11ghost --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "X11k";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11k --watchdog" }
#   [PSCustomObject]@{ Algorithm = "X12";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x12 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X13";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x13 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X14";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x14 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X15";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x15 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X16r";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 3; WarmupTimes = @(45, 60);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16r --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "X16rt";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16rt --watchdog" } # FPGA
    [PSCustomObject]@{ Algorithm = "X16rv2";           Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 3;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16rv2 --watchdog" }
    [PSCustomObject]@{ Algorithm = "X16s";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16s --watchdog" } # FPGA
    [PSCustomObject]@{ Algorithm = "X17";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x17 --watchdog" }
    [PSCustomObject]@{ Algorithm = "X18";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x18 --watchdog" }
    [PSCustomObject]@{ Algorithm = "X21s";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(120, 45); ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x21s --watchdog" } # Trex-v0.26.8 is fastest
    [PSCustomObject]@{ Algorithm = "X22";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x22 --watchdog" }
    [PSCustomObject]@{ Algorithm = "X22i";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x22i --watchdog" }
    [PSCustomObject]@{ Algorithm = "X25x";             Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x25x --watchdog" }
    [PSCustomObject]@{ Algorithm = "X33";              Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x33 --watchdog" }
    [PSCustomObject]@{ Algorithm = "Xevan";            Type = "INTEL"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo xevan --watchdog" }

    [PSCustomObject]@{ Algorithm = "Aergo";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo aergo --watchdog" }
    [PSCustomObject]@{ Algorithm = "Anime";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo anime --watchdog" }
    [PSCustomObject]@{ Algorithm = "AstralHash";       Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-astralhash --watchdog" }
    [PSCustomObject]@{ Algorithm = "BCD";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 3; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bcd --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "Bitcore";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bitcore --watchdog" }
    [PSCustomObject]@{ Algorithm = "Blake2bBtcc";      Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2b-btcc --watchdog" }
    [PSCustomObject]@{ Algorithm = "Blake2bGlt";       Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2b-glt --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Blake2s";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake2s --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "Blake3";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo blake3 --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Bmw512";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo bmw512 --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "C11";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 1; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo c11 --watchdog" }
    [PSCustomObject]@{ Algorithm = "CurveHash";        Type = "NVIDIA"; Fee = @(0.01);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo curvehash --watchdog" }
    [PSCustomObject]@{ Algorithm = "Dedal";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo dedal --watchdog" } # CryptoDredge-v0.27.0 is fastest
    [PSCustomObject]@{ Algorithm = "EvrProgPow";       Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 1; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo evrprogpow --watchdog" }
    [PSCustomObject]@{ Algorithm = "FiroPow";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 1.24; Minerset = 1; WarmupTimes = @(55, 30);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo firopow --watchdog" }
    [PSCustomObject]@{ Algorithm = "Ghostrider";       Type = "NVIDIA"; Fee = @(0.01);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(180, 60); ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo ghostrider --watchdog" }
    [PSCustomObject]@{ Algorithm = "GlobalHash";       Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-globalhash --watchdog" }
    [PSCustomObject]@{ Algorithm = "HeavyHash";        Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo heavyhash --watchdog" } # FPGA
    [PSCustomObject]@{ Algorithm = "Hex";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo hex --watchdog" }
    [PSCustomObject]@{ Algorithm = "HMQ1725";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 1; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo hmq1725 --watchdog" } # CryptoDredge-v0.27.0 is fastest
    [PSCustomObject]@{ Algorithm = "JeongHash";        Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-jeonghash --watchdog" } # Trex-v0.26.8 is fastest
    [PSCustomObject]@{ Algorithm = "KawPow";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 0.90; Minerset = 1; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo kawpow --watchdog" } # NBMiner-v42.3 is fastest
#   [PSCustomObject]@{ Algorithm = "Lyra2RE2";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2v2 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Lyra2RE3";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2v3 --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "Lyra2TDC";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2tdc --watchdog" }
    [PSCustomObject]@{ Algorithm = "Lyra2vc0ban";      Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo lyra2vc0ban --watchdog" }
    [PSCustomObject]@{ Algorithm = "MemeHash";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo memehash --watchdog" }
    [PSCustomObject]@{ Algorithm = "MegaBtx";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo megabtx --watchdog" }
    [PSCustomObject]@{ Algorithm = "Mike";             Type = "NVIDIA"; Fee = @(0.01);   MinMemGiB = 1;    MinerSet = 0; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo mike --watchdog" }
    [PSCustomObject]@{ Algorithm = "NexaPow";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 3;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @("NiceHash"); Arguments = " --algo nexapow --watchdog" } # https://github.com/andru-kun/wildrig-multi/issues/277
#   [PSCustomObject]@{ Algorithm = "Nist5";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 3;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo nist5 --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "PadiHash";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-padihash --watchdog" }
    [PSCustomObject]@{ Algorithm = "PawelHash";        Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo glt-pawelhash --watchdog" } # Trex-v0.26.8 is fastest
#   [PSCustomObject]@{ Algorithm = "Phi";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo phi --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Phi5";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo phi5 --watchdog" } # Algorithm is dead
    [PSCustomObject]@{ Algorithm = "ProgPowEthercore"; Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-ethercore --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowSero";      Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-sero --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowVeil";      Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpow-veil --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowVeriblock"; Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo vprogpow --watchdog" }
    [PSCustomObject]@{ Algorithm = "ProgPowZ";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 0.62; Minerset = 1; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo progpowz --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Pufferfish2BMB";   Type = "NVIDIA"; Fee = @(0.01);   MinMemGiB = 8;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo pufferfish2 --watchdog" } # waiting for coin to resurrect
    [PSCustomObject]@{ Algorithm = "RWAHash";          Type = "NVIDIA"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo rwahash --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Quark";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo quark --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "Quibit";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo qui --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "SHA256";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "SHA256d";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256d --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "SHAndwich256";     Type = "NVIDIA"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skydoge --watchdog" } # Trex-v0.26.8 is fastest
    [PSCustomObject]@{ Algorithm = "SHA256csm";        Type = "NVIDIA"; Fee = @(0.02);   MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256csm --watchdog" }
    [PSCustomObject]@{ Algorithm = "SHA256t";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256t --watchdog" }
    [PSCustomObject]@{ Algorithm = "SHA256q";          Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha256q --watchdog" }
    [PSCustomObject]@{ Algorithm = "SHA512256d";       Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @("Other"); ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo sha512256d --watchdog" }
    [PSCustomObject]@{ Algorithm = "Skein2";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(90, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skein2 --watchdog" } # CcminerAlexis78-v1.5.2 is fastest
    [PSCustomObject]@{ Algorithm = "SkunkHash";        Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(90, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo skunkhash --watchdog" } # Algorithm is dead
    [PSCustomObject]@{ Algorithm = "Timetravel";       Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo timetravel --watchdog" }
    [PSCustomObject]@{ Algorithm = "Timetravel10";     Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo timetravel10 --watchdog" }
#   [PSCustomObject]@{ Algorithm = "Tribus";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo tribus --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X11";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X11ghost";         Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11ghost --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "X11k";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x11k --watchdog" }
#   [PSCustomObject]@{ Algorithm = "X12";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x12 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X13";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x13 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X14";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x14 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X15";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x15 --watchdog" } # ASIC
#   [PSCustomObject]@{ Algorithm = "X16r";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 3; WarmupTimes = @(45, 60);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16r --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "X16rt";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(45, 0);   ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16rt --watchdog" } # FPGA
    [PSCustomObject]@{ Algorithm = "X16rv2";           Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 3;    MinerSet = 0; WarmupTimes = @(45, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16rv2 --watchdog" }
    [PSCustomObject]@{ Algorithm = "X16s";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x16s --watchdog" } # FPGA
    [PSCustomObject]@{ Algorithm = "X17";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x17 --watchdog" }
    [PSCustomObject]@{ Algorithm = "X18";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x18 --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "X20r";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x20r --watchdog" } # ASIC
    [PSCustomObject]@{ Algorithm = "X21s";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    MinerSet = 0; WarmupTimes = @(120, 45); ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x21s --watchdog" } # Trex-v0.26.8 is fastest
    [PSCustomObject]@{ Algorithm = "X22";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x22 --watchdog" }
#   [PSCustomObject]@{ Algorithm = "X22i";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x22i --watchdog" } # Not yet supported on Nvidia
#   [PSCustomObject]@{ Algorithm = "X25x";             Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x25x --watchdog" } # Not yet supported on Nvidia
    [PSCustomObject]@{ Algorithm = "X33";              Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(30, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo x33 --watchdog" }
    [PSCustomObject]@{ Algorithm = "Xevan";            Type = "NVIDIA"; Fee = @(0.0075); MinMemGiB = 2;    Minerset = 2; WarmupTimes = @(60, 15);  ExcludeGPUArchitecture = @();        ExcludeGPUModel = ""; ExcludePools = @();           Arguments = " --algo xevan --watchdog" }
)

$Algorithms = $Algorithms.Where({ $_.MinerSet -le $Config.MinerSet })
$Algorithms = $Algorithms.Where({ $MinerPools[0][$_.Algorithm] })
$Algorithms = $Algorithms.Where({ $MinerPools[0][$_.Algorithm].Name -notin $_.ExcludePools })

If ($Algorithms) { 

    ($Devices | Select-Object Type, Model -Unique).ForEach(
        { 
            $Miner_Devices = $Devices | Where-Object Type -EQ $_.Type | Where-Object Model -EQ $_.Model
            $MinerAPIPort = $Config.APIPort + ($Miner_Devices.Id | Sort-Object -Top 1) + 1

            ($Algorithms | Where-Object Type -EQ $_.Type).ForEach(
                { 
                    If ($AvailableMiner_Devices = If ($_.ExcludeGPUModel) { $Miner_Devices.Where({ $_.Model -notmatch $_.ExcludeGPUModel }) } Else { $Miner_Devices }) { 
                        $ExcludePools = $_.ExcludePools
                        ForEach ($Pool in ($MinerPools[0][$_.Algorithm].Where({ $_.Name -notin $ExcludePools }))) { 

                            $ExcludeGPUArchitecture = $_.ExcludeGPUArchitecture
                            $MinMemGiB = $_.MinMemGiB + $Pool.DAGSizeGiB
                            If ($AvailableMiner_Devices = $AvailableMiner_Devices.Where({ $_.MemoryGiB -GE $MinMemGiB -and $_.Architecture -notin $ExcludeGPUArchitecture })) { 

                                $Miner_Name = "$Name-$($AvailableMiner_Devices.Count)x$($AvailableMiner_Devices.Model | Select-Object -Unique)"

                                [PSCustomObject]@{ 
                                    API         = "XmRig"
                                    Arguments   = "$($_.Arguments) --api-port $MinerAPIPort --url $(If ($Pool.PoolPorts[1]) { "stratum+tcps" } Else { "stratum+tcp" })://$($Pool.Host):$($Pool.PoolPorts | Select-Object -Last 1) --user $($Pool.User) --pass $($Pool.Pass) --multiple-instance --opencl-devices $(($AvailableMiner_Devices.$DeviceEnumerator | Sort-Object -Unique).ForEach({ '{0:x}' -f $_ }) -join ',')"
                                    DeviceNames = $AvailableMiner_Devices.Name
                                    Fee         = @($_.Fee) # Dev fee
                                    MinerSet    = $_.MinerSet
                                    MinerUri    = "http://127.0.0.1:$($MinerAPIPort)"
                                    Name        = $Miner_Name
                                    Path        = $Path
                                    Port        = $MinerAPIPort
                                    Type        = $_.Type
                                    URI         = $Uri
                                    WarmupTimes = $_.WarmupTimes # First value: Seconds until miner must send first sample, if no sample is received miner will be marked as failed; Second value: Seconds from first sample until miner sends stable hashrates that will count for benchmarking
                                    Workers     = @(@{ Pool = $Pool })
                                }
                            }
                        }
                    }
                }
            )
        }
    )
}