If (-not (IsLoaded(".\Includes\include.ps1"))) { . .\Includes\include.ps1; RegisterLoaded(".\Includes\include.ps1") }
$Path = ".\Bin\AMD-nanominer315\nanominer.exe"
$Uri = "https://github.com/nanopool/nanominer/releases/download/v3.1.5/nanominer-windows-3.1.5-cuda11.zip"
$Commands = [PSCustomObject]@{ 
     "Ubqhash" = "" #
  
}

$Name = "$(Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName)"
$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object { $Algo = Get-Algorithm $_; $_ } | Where-Object { $Pools.$Algo.Host } | ForEach-Object { 
    Switch ($_) { 
        "randomhash" { $Fee = 0.05 } # substract devfee
        default { $Fee = 0.01 } # substract devfee
    }

    $ConfigFileName = "$((@("Config") + @($Algo) + @($Algorithm_Norm) + @($Variables.CPUMinerAPITCPPort) + @($Pools.$Algo.User) | Select-Object) -join '-').ini"
    $Arguments = [PSCustomObject]@{ 
        ConfigFile = [PSCustomObject]@{ 
        FileName = $ConfigFileName
        Content  = "
; NemoMiner autogenerated config file (c) nemosminer.com
checkForUpdates=false
mport=0
noLog=true
rigName=$($Config.WorkerName)
watchdog=false
webPort=$($Variables.AMDMinerAPITCPPort)

[$($_)]
pool1=$($Pools.$Algo.Host):$($Pools.$Algo.Port)
wallet=$($Pools.$Algo.User)"
        }
        Commands = "$ConfigFileName"
    }

    [PSCustomObject]@{ 
        Type      = "AMD"
        Path      = $Path
        Arguments = $Arguments
        HashRates = [PSCustomObject]@{ $Algo = $Stats."$($Name)_$($Algo)_HashRate".Week * (1 - $Fee) } # substract devfee
        API       = "nanominer"
        Port      = $Variables.AMDMinerAPITCPPort
        Wrap      = $false
        URI       = $Uri
    }
}
